version: "3.8"

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # Веб-интерфейс управления RabbitMQ
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  lostfound_service:
    build:
      context: ./lost_found_service
      dockerfile: ./Dockerfile
    container_name: lostfound_service
    ports:
      - "8000:8000"
    environment:
      DB_HOST: lostfound_db
      DB_PORT: 5432
      DB_NAME: LostAndFoundDB_ref
      DB_USER: postgres
      DB_PASSWORD: postgres
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    volumes:
      - ./lost_found_service:/app
    depends_on:
      - lostfound_db
      - rabbitmq

  lostfound_db:
    image: postgres:15.3
    container_name: lostfound_db
    environment:
      POSTGRES_DB: LostAndFoundDB_ref
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - lostfound_db_data:/var/lib/postgresql/data

  auth_service:
    build:
      context: ./auth_service
      dockerfile: ./Dockerfile
    container_name: auth_service
    ports:
      - "8003:8003"
    environment:
      DB_HOST: auth_db
      DB_PORT: 5432
      DB_NAME: AuthDB
      DB_USER: postgres
      DB_PASSWORD: postgres
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    volumes:
      - ./auth_service:/app
    depends_on:
      - auth_db
      - rabbitmq

  auth_db:
    image: postgres:15.3
    container_name: auth_db
    environment:
      POSTGRES_DB: AuthDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  auction_service:
    build:
      context: ./auction_service
      dockerfile: ./Dockerfile
    container_name: auction_service
    ports:
      - "8004:8004"
    environment:
      DB_HOST: auction_db
      DB_PORT: 5432
      DB_NAME: AuctionDB
      DB_USER: postgres
      DB_PASSWORD: postgres
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    volumes:
      - ./auction_service:/app
    depends_on:
      - rabbitmq
      - auction_db

  auction_db:
    image: postgres:15.3
    container_name: auction_db
    environment:
      POSTGRES_DB: AuctionDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - auction_db_data:/var/lib/postgresql/data

#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    depends_on:
#      - auth_service
#      - lostfound_service
#      - auction_service

volumes:
  lostfound_db_data:
  auth_db_data:
  auction_db_data:
  rabbitmq_data:
